from datetime import datetime, UTC


class IntelligenceDecisionService:


    def build(
        self,
        reasoning=None,
        recommendation=None,
        memory=None,
    ):

        decision = {
            "action": None,
            "confidence": 0,
            "risk": "UNKNOWN",
            "source": "none",
            "diagnosis": {},
            "diagnoses": [],
            "reasons": [],
            "evidence": [],
            "generated_at":
                datetime.now(UTC).isoformat(),
        }


        #
        # Preserve structured diagnoses generated by
        # the reasoning engine.
        #
        # "diagnoses" is the authoritative structured
        # diagnostic collection. A single incident may
        # contain multiple independent diagnoses.
        #
        if reasoning:

            diagnoses = reasoning.get(
                "diagnoses",
                [],
            )

            if diagnoses:

                decision["diagnoses"] = list(
                    diagnoses
                )

                #
                # Backward compatibility for consumers
                # that still expect a singular diagnosis.
                #
                decision["diagnosis"] = diagnoses[0]

        if recommendation:

            #
            # ActionPlan is the canonical domain contract.
            # Keep dictionary compatibility for legacy callers.
            #
            if hasattr(
                recommendation,
                "action",
            ) and hasattr(
                recommendation,
                "confidence",
            ):

                action = recommendation.action

                confidence = recommendation.confidence

                risk = recommendation.risk

                reasons = recommendation.reason

                evidence = recommendation.evidence

            else:

                action = recommendation.get(
                    "action"
                )

                confidence = recommendation.get(
                    "confidence",
                    0,
                )

                risk = recommendation.get(
                    "risk",
                    "UNKNOWN",
                )

                reasons = recommendation.get(
                    "reason",
                    [],
                )

                evidence = recommendation.get(
                    "evidence",
                    [],
                )

            if action:

                decision["action"] = action

                decision["confidence"] = confidence

                decision["risk"] = risk

                decision["source"] = "recommendation"

                if reasons:

                    if isinstance(
                        reasons,
                        list,
                    ):

                        decision["reasons"].extend(
                            reasons
                        )

                    else:

                        decision["reasons"].append(
                            reasons
                        )

                if evidence:

                    decision["evidence"].extend(
                        evidence
                    )


        #
        # Diagnosis-driven decision.
        #
        # If neither recommendation nor reasoning produced
        # an action, use the structured diagnosis as the
        # deterministic operational fallback.
        #
        if (
            not decision["action"]
            and reasoning
        ):

            diagnoses = reasoning.get(
                "diagnoses",
                []
            )

            if diagnoses:

                diagnosis = diagnoses[0]

                diagnosis_type = diagnosis.get(
                    "type"
                )

                diagnosis_actions = {

                    "DNS_FAILURE": (
                        "inspect logs",
                        "LOW",
                    ),

                    "STORAGE_HEALTH_FAILURE": (
                        "inspect SMART",
                        "HIGH",
                    ),

                    "HIGH_TEMPERATURE": (
                        "inspect temperature",
                        "LOW",
                    ),

                }

                mapped = diagnosis_actions.get(
                    diagnosis_type
                )

                if mapped:

                    action, risk = mapped

                    decision["action"] = action

                    decision["confidence"] = diagnosis.get(
                        "confidence",
                        0,
                    )

                    decision["risk"] = risk

                    decision["source"] = "diagnosis"

                    decision["reasons"].append(
                        f"diagnosis-driven action: "
                        f"{diagnosis_type}"
                    )

                    evidence = diagnosis.get(
                        "evidence"
                    )

                    if evidence:

                        decision["evidence"].append(
                            {
                                "source": "diagnosis",
                                "diagnosis": diagnosis_type,
                                "observation": evidence,
                            }
                        )


        if reasoning:

            actions = reasoning.get(
                "recommended_actions",
                []
            )

            if actions and not decision["action"]:

                action = actions[0]

                decision["action"] = action.get(
                    "action"
                )

                decision["confidence"] = 0.9

                decision["risk"] = action.get(
                    "risk",
                    "UNKNOWN"
                )

                decision["source"] = "reasoning"

                decision["reasons"].append(
                    action.get(
                        "reason",
                        "reasoning engine"
                    )
                )


        if memory:

            matches = memory.get(
                "similar_cases",
                0
            )

            if matches:

                decision["confidence"] = min(
                    1.0,
                    decision["confidence"] + 0.05
                )

                decision["reasons"].append(
                    f"{matches} similar historical case(s)"
                )

                decision["evidence"].extend(
                    memory.get(
                        "evidence",
                        []
                    )
                )


        return decision
